### ISSUE TITLE
is it possible to add dfw rule but keep it disabled?

### ISSUE THREAD

**Issue by githubuser00** [lamw/VMware.VMC.NSXT#17]
is it possible to add dfw rule with New-NSXTDistFirewall but keep it disabled?

![image](https://user-images.githubusercontent.com/7738909/194226665-b626cbe4-b3e1-4e4b-bfe1-aa682dfb1c92.png)

**Comment by lamw** [comment]
Yes, if the UI allows it, its possible :) 

The VMC NSX-T API Documentation is at https://developer.vmware.com/apis/nsx-vmc-policy/v1.0/ and for adding a DFW Rule, its known as a`CommunicationEntry` where you can see there is a `disabled` property (its false by default). Simply add this additional field to https://github.com/lamw/VMware.VMC.NSXT/blob/master/VMware.VMC.NSXT.psm1#L1863-L1872 

Of course you can update function definition to accept another optional parameter on whether to enable or disable DFW by default

**Comment by githubuser00** [comment]
thank you. it worked.

![image](https://user-images.githubusercontent.com/7738909/194382947-e8025b2d-c666-4a05-b1e3-db14425b5eb0.png)

![image](https://user-images.githubusercontent.com/7738909/194383004-63f8fac2-eba4-4f66-8b10-d900771560da.png)
