### ISSUE TITLE
New-NSXTDistFirewall function bug

### ISSUE THREAD

**Issue by fujimorii** [lamw/VMware.VMC.NSXT#6]
It would be helpful if you could fix line 1658 of the New-NSXTDistFirewall function as follows:

```diff
- $tmp = "/infra/services/$serviceName"
+ $tmp = (Get-NSXTServiceDefinition -Name "$serviceName").Path
```
https://github.com/lamw/VMware.VMC.NSXT/blob/a4f485e5b9739639d6397e406673609404a634a7/VMware.VMC.NSXT.psm1#L1653-L1661

**Comment by lamw** [comment]
Fixed

**Comment by fujimorii** [comment]
Thank you for your support
